org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
# ForgeGradle 6 and MixinGradle do not support Gradle configuration cache reliably.
org.gradle.configuration-cache=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.21
forge_version_range=[47.4.21,48)
loader_version_range=[47,)
jei_version=15.20.0.133
brandons_core_version=1.20.1-3.2.1.302
chicken_version=1.20.1-4.4.0.516
draconic_evolution_version=1.20.1-3.1.2.621
mod_id=chaotic_energy_crystal
mod_name=Chaotic Energy Crystal
mod_license=MIT
mod_version=1.0.1
mod_group_id=com.jerry
mod_authors=Lost Myself
mod_description=Add chaotic energy crystal to Draconic Evolution.